---
- name: Delete user and group
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    username: cloud
    groupname: aws
  tasks:
  - name: Delete a user
    user:
      name: "{{username}}"
      state: absent

  - name: Delete group
    group:
      name: "{{groupname}}"
      state: absent
