---
- name: Create a new user
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    username: cloud
    groupname: aws
  tasks:
  - name: Create group
    group:
      name: "{{groupname}}"
      state: present

  - name: Create a user
    user:
      name: "{{username}}"
      group: "{{groupname}}"
      state: present
      shell: /bin/bash