---
- name: Install Java for Debian ubuntu
  hosts: localhost
  become: yes
  vars_prompt:
    - name: java_version
      prompt: Enter Java Version
      private: no 
  tasks:
   - name: Download Java Tar file
     get_url:
        url: https://download.oracle.com/java/{{ java_version}}/archive/jdk-{{ java_version}}_linux-x64_bin.tar.gz
        dest: /tmp/jdk-{{ java_version}}_linux-x64_bin.tar.gz
        validate_certs: no
        headers:
          Cookie: "oraclelicense=accept-securebackup-cookie"
    
   - name: Extract Java Archive
     ansible.builtin.unarchive:
       src: /tmp/jdk-{{ java_version }}_linux-x64_bin.tar.gz
       dest: /usr/lib/jvm
       creates: /usr/lib/jvm/jdk-{{ java_version }}
     
   - name: Remove tar file
     file:
        path: /tmp/jdk-{{ java_version }}_linux-x64_bin.tar.gz
        state: absent

   - name: Set JAVA_HOME environment variable
     lineinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        line: "export JAVA_HOME=/usr/lib/jvm/jdk-{{ java_version }}"
        create: yes

   - name: Add Java binaries to PATH
     lineinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        line: "export PATH=$PATH:/usr/lib/jvm/jdk-{{ java_version }}/bin"
        create: yes

   - name: Update alternatives for java
     alternatives:
        name: java
        path: /usr/lib/jvm/jdk-{{ java_version }}/bin/java
        state: present
        priority: 2

   - name: Update alternatives for javac
     alternatives:
        name: javac
        path: /usr/lib/jvm/jdk-{{ java_version }}/bin/javac
        state: present
        priority: 2
   
   - name: Verify Java Installation
     shell: |
      java -version
     register: version

   - debug:
      msg:  
      - "Java installed Successfully!!!"
      - "Installed java version is : {{ version }} "