---
- name: Install nginx on ubuntu
  hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
          - name: Install nginx
            apt:
                  name: nginx
                  state: present
                  
          - name: Enable service
            service:
                    name: Starting nginx service
                    status: started
                    enabled: true
