---
- name: Install nginx on ubuntu
  hosts: localhost
  become: yes
  tasks:
          - name: Install nginx
            apt:
                  name: nginx-core
                  state: present
                  
          - name: Start nginx service
            service:
              name: nginx
              state: started